### ISSUE TITLE
Creating Model instance in View

### ISSUE THREAD

**Issue by sandeepyohans** [mitchtabian/MVVMExample1#1]
Hello Mitch, thanks a ton for sharing this project. 
With respect to line 68 in MainActivity, by calling NicePlace constructer in MainActivity, are we not violating the MVVM architecture guideline? If yes then what is the better way to do it?﻿ I am new to MVVM and trying to understand the architecture so that I can implement it in my current project.
Thanks.

**Comment by mitchtabian** [comment]
This is just an example.
Usually you wouldn't just be adding data to a list randomly like I am. You would be reading it from the network or a database cache. So normally what you'd do if you wanted to insert some new data (which I'm assuming is your question) is:

1. Insert the data into the cache (or the network, depending on what you're doing)
2. Observe the changes to the cache or network using LiveData. 

So you wouldn't be inserting data into the ViewModel like I am in this example. You want to insert the data where it belongs, and then observe the changes to that location with LiveData.

**I highly recommend watching this:** https://codingwithmitch.com/courses/rest-api-mvvm-retrofit2/
