### ISSUE TITLE
setValue fails on first run on actual network call

### ISSUE THREAD

**Issue by Alecckie** [mitchtabian/MVVMExample1#2]
The repository **setValue** call works fine with the hard coded data.
It however fails to update the view on first run when loading data from network using Volley.
**It populates the views on refresh but not on first run**
I dont understand why or where I'm supposed to make change. 
Its like the viewModel and the views load first then the data comes in a few seconds later - I can see the data on Toast-  but that data is not loaded in the UI.
Using **postValue** doesnt update the views at all

**Sample repository setValue function**
<pre>
public MutableLiveData<List<DecodeHouseDetails>> getHouseDetails(Context mContext){
        this.mContext=mContext;

        getDatabaseHouseDetails();

        MutableLiveData<List<DecodeHouseDetails>> myData= new MutableLiveData<>();
        myData.setValue(dataSet);
        return myData;
    }
</pre>

**Sample repository network call** _getDatabaseHouseDetails();_ **in volley**
<pre>@Override
public void onSuccessResponse(String response) {
	Log.e("Response", response);
	if(response!=null) {
		try {
			JSONObject json = new JSONObject(response);
			//Successfully fetched

			String sarray = json.getString("house_details");
			Toast.makeText(mContext, sarray, Toast.LENGTH_SHORT).show();
			JSONArray jsonArray = new JSONArray(sarray);

			//Clear list to refresh list in every selection
			for (int i = 0; i < jsonArray.length(); i++) {
				JSONObject json_list = jsonArray.getJSONObject(i);
				DecodeHouseDetails houses_array = new DecodeHouseDetails(
						json_list.getInt("active_identifier"),
						json_list.getInt("house_id"),
						json_list.getInt("house_status"),
						json_list.getString("house_number"),
						json_list.getString("house_cover"),
						json_list.getString("house_name"),
						json_list.getString("longitude"),
						json_list.getString("latitude")
				);
				dataSet.add(houses_array);
			}

		} catch (JSONException e) {
			e.printStackTrace();
			//Dismiss loader
			isUpdating = false;
		}
	}
}</pre>

**Comment by mitchtabian** [comment]
You should watch my MVVM and Retrofit course. I show you how to do this properly.
If money is an issue email me and I'll give you a free 2 weeks on codingwithmitch.com.
https://codingwithmitch.com/courses/rest-api-mvvm-retrofit2/
